SET IDENTITY_INSERT [dbo].[SchoolDisciplines] ON
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (1, N'Математика')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (2, N'Алгебра')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (3, N'Геометрия')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (4, N'Статистика')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (5, N'Экономика')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (6, N'Информатика')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (7, N'Геограифия')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (8, N'Биология')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (9, N'Астрономия')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (10, N'Физика')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (11, N'Химия')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (12, N'ОБЖ')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (13, N'История')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (14, N'Обществознания')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (15, N'Русский язык')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (16, N'Литература')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (17, N'Иностранный язык')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (18, N'Труд')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (19, N'Черчение')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (20, N'Физкультура')
INSERT INTO [dbo].[SchoolDisciplines] ([Id], [Name]) VALUES (21, N'ИЗО')
SET IDENTITY_INSERT [dbo].[SchoolDisciplines] OFF
