//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Preference = new HashSet<Preference>();
            this.University = new HashSet<University>();
            this.School = new HashSet<School>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Prestige { get; set; }
    
        public virtual ICollection<Preference> Preference { get; set; }
        public virtual ICollection<University> University { get; set; }
        public virtual ICollection<School> School { get; set; }
    }
}
