//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Preference = new HashSet<Preference>();
            this.University = new HashSet<University>();
            this.School = new HashSet<School>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Prestige { get; set; }
    
        public virtual ICollection<Preference> Preference { get; set; }
        public virtual ICollection<University> University { get; set; }
        public virtual ICollection<School> School { get; set; }
    }
}
