//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Competition
    {
        public Competition()
        {
            this.ParticipationInCompetition = new HashSet<ParticipationInCompetition>();
            this.Weight = new HashSet<Weight>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<ParticipationInCompetition> ParticipationInCompetition { get; set; }
        public virtual ICollection<Weight> Weight { get; set; }
    }
}
