//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentLinesRequirement
    {
        public int Id { get; set; }
        public int Requirement { get; set; }
        public int DepartmentEducationLineId { get; set; }
        public int DisciplineId { get; set; }
    
        public virtual DepartmentEducationLine DepartmentEducationLine { get; set; }
        public virtual Discipline Discipline { get; set; }
    }
}
