//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentEducationLine
    {
        public DepartmentEducationLine()
        {
            this.DepartmentLinesRequirement = new HashSet<DepartmentLinesRequirement>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int GeneralEducationLineId { get; set; }
        public int UniversityDepartmentId { get; set; }
        public string EducationForm { get; set; }
    
        public virtual GeneralEducationLine GeneralEducationLine { get; set; }
        public virtual UniversityDepartment UniversityDepartment { get; set; }
        public virtual ICollection<DepartmentLinesRequirement> DepartmentLinesRequirement { get; set; }
    }
}
