//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepartmentEducationLine
    {
        public DepartmentEducationLine()
        {
            this.DepartmentLinesRequirement = new HashSet<DepartmentLinesRequirement>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int GeneralEducationLineId { get; set; }
        public int UniversityDepartmentId { get; set; }
        public string EducationForm { get; set; }
    
        public virtual GeneralEducationLine GeneralEducationLine { get; set; }
        public virtual UniversityDepartment UniversityDepartment { get; set; }
        public virtual ICollection<DepartmentLinesRequirement> DepartmentLinesRequirement { get; set; }
    }
}
