//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public Discipline()
        {
            this.UnitedStateExam = new HashSet<UnitedStateExam>();
            this.DepartmentLinesRequirement = new HashSet<DepartmentLinesRequirement>();
            this.Weight = new HashSet<Weight>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<UnitedStateExam> UnitedStateExam { get; set; }
        public virtual ICollection<DepartmentLinesRequirement> DepartmentLinesRequirement { get; set; }
        public virtual ICollection<Weight> Weight { get; set; }
    }
}
