//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Discipline
    {
        public Discipline()
        {
            this.UnitedStateExam = new HashSet<UnitedStateExam>();
            this.DepartmentLinesRequirement = new HashSet<DepartmentLinesRequirement>();
            this.Weight = new HashSet<Weight>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<UnitedStateExam> UnitedStateExam { get; set; }
        public virtual ICollection<DepartmentLinesRequirement> DepartmentLinesRequirement { get; set; }
        public virtual ICollection<Weight> Weight { get; set; }
    }
}
