//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralEducationLine
    {
        public GeneralEducationLine()
        {
            this.DepartmentEducationLine = new HashSet<DepartmentEducationLine>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Actual { get; set; }
        public int ClusterId { get; set; }
    
        public virtual Cluster Cluster { get; set; }
        public virtual ICollection<DepartmentEducationLine> DepartmentEducationLine { get; set; }
    }
}
