//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParticipationInCompetition
    {
        public int Id { get; set; }
        public string Result { get; set; }
        public int UserId { get; set; }
        public int CompetitionId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Competition Competition { get; set; }
    }
}
