//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preference
    {
        public Preference()
        {
            this.City = new HashSet<City>();
        }
    
        public int Id { get; set; }
        public int Presige { get; set; }
        public string EducationFrom { get; set; }
        public int UserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<City> City { get; set; }
    }
}
