//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecomendationSystemModelContainer : DbContext
    {
        public RecomendationSystemModelContainer()
            : base("name=RecomendationSystemModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Section> Sections { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<SchoolType> SchoolTypes { get; set; }
        public DbSet<School> Schools { get; set; }
        public DbSet<Preference> Preferences { get; set; }
        public DbSet<Hobbie> Hobbies { get; set; }
        public DbSet<ParticipationInCompetition> ParticipationInCompetitions { get; set; }
        public DbSet<Competition> Competitions { get; set; }
        public DbSet<UnitedStateExam> UnitedStateExams { get; set; }
        public DbSet<SchoolMark> SchoolMarks { get; set; }
        public DbSet<Discipline> Disciplines { get; set; }
        public DbSet<Cluster> Clusters { get; set; }
        public DbSet<University> HighSchools { get; set; }
        public DbSet<City> Cities { get; set; }
        public DbSet<UniversityDepartment> UniversityDepartments { get; set; }
        public DbSet<DepartmentEducationLine> DepartmentEducationLines { get; set; }
        public DbSet<GeneralEducationLine> GeneralEducationLines { get; set; }
        public DbSet<DepartmentLinesRequirement> DepartmentLinesRequirements { get; set; }
        public DbSet<SchoolDiscipline> SchoolDisciplines { get; set; }
        public DbSet<Weight> Weights { get; set; }
    }
}
