//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RecomendationSystemModelContainer : DbContext
    {
        public RecomendationSystemModelContainer()
            : base("name=RecomendationSystemModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Section> Sections { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<SchoolType> SchoolTypes { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Preference> Preferences { get; set; }
        public virtual DbSet<Hobbie> Hobbies { get; set; }
        public virtual DbSet<ParticipationInCompetition> ParticipationInCompetitions { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<UnitedStateExam> UnitedStateExams { get; set; }
        public virtual DbSet<SchoolMark> SchoolMarks { get; set; }
        public virtual DbSet<Discipline> Disciplines { get; set; }
        public virtual DbSet<Cluster> Clusters { get; set; }
        public virtual DbSet<University> HighSchools { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<UniversityDepartment> UniversityDepartments { get; set; }
        public virtual DbSet<DepartmentEducationLine> DepartmentEducationLines { get; set; }
        public virtual DbSet<GeneralEducationLine> GeneralEducationLines { get; set; }
        public virtual DbSet<DepartmentLinesRequirement> DepartmentLinesRequirements { get; set; }
        public virtual DbSet<SchoolDiscipline> SchoolDisciplines { get; set; }
        public virtual DbSet<Weight> Weights { get; set; }
    }
}
