//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int EducationQuality { get; set; }
        public int SchoolTypeId { get; set; }
    
        public virtual ICollection<User> User { get; set; }
        public virtual SchoolType SchoolType { get; set; }
        public virtual City City { get; set; }
    }
}
