//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolMark
    {
        public int Id { get; set; }
        public short Result { get; set; }
        public Nullable<int> Respect { get; set; }
        public int UserId { get; set; }
        public int SchoolDisciplineId { get; set; }
    
        public virtual User User { get; set; }
        public virtual SchoolDiscipline SchoolDiscipline { get; set; }
    }
}
