//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolMark
    {
        public int Id { get; set; }
        public short Result { get; set; }
        public Nullable<int> Respect { get; set; }
        public int UserId { get; set; }
        public int SchoolDisciplineId { get; set; }
    
        public virtual User User { get; set; }
        public virtual SchoolDiscipline SchoolDiscipline { get; set; }
    }
}
