//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class School
    {
        public School()
        {
            this.User = new HashSet<User>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int EducationQuality { get; set; }
        public int SchoolTypeId { get; set; }
    
        public virtual ICollection<User> User { get; set; }
        public virtual SchoolType SchoolType { get; set; }
        public virtual City City { get; set; }
    }
}
