//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.User = new HashSet<User>();
            this.Weight = new HashSet<Weight>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string ActivityType { get; set; }
        public int Period { get; set; }
    
        public virtual ICollection<User> User { get; set; }
        public virtual ICollection<Weight> Weight { get; set; }
    }
}
