//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitedStateExam
    {
        public int Id { get; set; }
        public int Result { get; set; }
        public int DisciplineId { get; set; }
        public int UserId { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual User User { get; set; }
    }
}
