//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitedStateExam
    {
        public int Id { get; set; }
        public int Result { get; set; }
        public int DisciplineId { get; set; }
        public int UserId { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual User User { get; set; }
    }
}
