//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversityDepartment
    {
        public UniversityDepartment()
        {
            this.DepartmentEducationLine = new HashSet<DepartmentEducationLine>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Prestige { get; set; }
        public int UniversityId { get; set; }
    
        public virtual University University { get; set; }
        public virtual ICollection<DepartmentEducationLine> DepartmentEducationLine { get; set; }
    }
}
