//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Section = new HashSet<Section>();
            this.Hobbie = new HashSet<Hobbie>();
            this.School = new HashSet<School>();
            this.Preference = new HashSet<Preference>();
            this.ParticipationInCompetition = new HashSet<ParticipationInCompetition>();
            this.UnitedStateExam = new HashSet<UnitedStateExam>();
            this.SchoolMark = new HashSet<SchoolMark>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SchoolEducation { get; set; }
    
        public virtual ICollection<Section> Section { get; set; }
        public virtual ICollection<Hobbie> Hobbie { get; set; }
        public virtual ICollection<School> School { get; set; }
        public virtual ICollection<Preference> Preference { get; set; }
        public virtual ICollection<ParticipationInCompetition> ParticipationInCompetition { get; set; }
        public virtual ICollection<UnitedStateExam> UnitedStateExam { get; set; }
        public virtual ICollection<SchoolMark> SchoolMark { get; set; }
    }
}
